"""Add description colum to experience

Revision ID: 620c143e9880
Revises: 3c07bcd188b4
Create Date: 2025-02-20 14:27:03.000454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620c143e9880'
down_revision = '3c07bcd188b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('tech_used')
        batch_op.drop_column('responsibilities')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsibilities', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('tech_used', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
